blueprint:
  name: easyjob Timecard: Auto Time Tracking
  description: >
    Startet/stoppt einen Zeiterfassungs-Schalter beim Betreten/Verlassen einer Zone ODER via Zusatztrigger (Kalender/Binary Sensor).
    Unterstützt bis zu 2 Pausenfenster und optional Confirmable Notifications.
  domain: automation
  input:
    tracking_switch:
      name: Zeiterfassung-Schalter
      description: Schalter/Helper, der die Zeiterfassung an/aus schaltet (z.B. input_boolean oder switch).
      selector:
        entity: {}

    presence_entity:
      name: Präsenz-Entity
      description: Person oder Device Tracker, dessen Zone-Status verwendet wird.
      selector:
        entity:
          domain:
            - person
            - device_tracker

    work_zone:
      name: Arbeitszone
      description: Zone, deren Betreten/Verlassen Start/Stop auslöst.
      selector:
        entity:
          domain: zone

    # ---- Pausenfenster 1 ----
    pause1_enabled:
      name: Pause 1 aktiv
      default: false
      selector:
        boolean: {}
    pause1_start:
      name: Pause 1 Start
      default: "12:00:00"
      selector:
        time: {}
    pause1_end:
      name: Pause 1 Ende
      default: "12:30:00"
      selector:
        time: {}

    # ---- Pausenfenster 2 ----
    pause2_enabled:
      name: Pause 2 aktiv
      default: false
      selector:
        boolean: {}
    pause2_start:
      name: Pause 2 Start
      default: "00:00:00"
      selector:
        time: {}
    pause2_end:
      name: Pause 2 Ende
      default: "00:00:00"
      selector:
        time: {}

    # ---- Zusätzlicher Binary Sensor Trigger ----
    extra_binary_enabled:
      name: Zusätzlichen Binary Sensor Trigger nutzen
      default: false
      selector:
        boolean: {}
    extra_binary_sensor:
      name: Binary Sensor (Start bei ON, Stop bei OFF)
      description: Optionaler Trigger, der zusätzlich zur Zone zählt (ODER).
      default: ""
      selector:
        entity:
          domain: binary_sensor

    # ---- Kalender Trigger ----
    calendar_enabled:
      name: Kalender-Trigger nutzen
      default: false
      selector:
        boolean: {}
    calendar_entity:
      name: Kalender
      default: ""
      selector:
        entity:
          domain: calendar
    calendar_title_contains:
      name: Kalender-Titel enthält (Filter)
      description: Wenn leer, wird jedes Event genutzt. Sonst nur Events, deren Titel diesen Text enthält (case-insensitive).
      default: ""
      selector:
        text: {}

    # ---- Bestätigung via Notification ----
    confirm_changes:
      name: Start/Stop per Notification bestätigen lassen
      default: false
      selector:
        boolean: {}
    notify_service:
      name: Notify-Service (für Confirmable Notifications)
      description: z.B. notify.mobile_app_dein_handy (muss Actions unterstützen). Wenn confirm aus ist, egal.
      default: "notify.notify"
      selector:
        text: {}

mode: single

variables:
  tracking_switch: !input tracking_switch
  presence_entity: !input presence_entity
  work_zone: !input work_zone

  pause1_enabled: !input pause1_enabled
  pause1_start: !input pause1_start
  pause1_end: !input pause1_end
  pause2_enabled: !input pause2_enabled
  pause2_start: !input pause2_start
  pause2_end: !input pause2_end

  extra_binary_enabled: !input extra_binary_enabled
  extra_binary_sensor: !input extra_binary_sensor
  calendar_enabled: !input calendar_enabled
  calendar_entity: !input calendar_entity
  calendar_title_contains: !input calendar_title_contains

  confirm_changes: !input confirm_changes
  notify_service: !input notify_service

  # --- Hilfsfunktionen: Prüfen ob "now" innerhalb eines Pause-Fensters liegt (auch über Mitternacht) ---
  is_in_window: >-
    {% macro inwin(enabled, start, end) -%}
      {%- if not enabled -%}
        false
      {%- else -%}
        {%- set s = today_at(start) -%}
        {%- set e = today_at(end) -%}
        {%- set n = now() -%}
        {%- if e > s -%}
          {{ s <= n < e }}
        {%- else -%}
          {{ (n >= s) or (n < e) }}
        {%- endif -%}
      {%- endif -%}
    {%- endmacro -%}
    {{ inwin(pause1_enabled, pause1_start, pause1_end) or inwin(pause2_enabled, pause2_start, pause2_end) }}

  zone_ok_now: >-
    {{ state_attr(presence_entity, 'latitude') is not none
       and states(presence_entity) == state_attr(work_zone, 'friendly_name') }}

trigger:
  # Zone enter/leave
  - platform: zone
    entity_id: !input presence_entity
    zone: !input work_zone
    event: enter
    id: zone_enter

  - platform: zone
    entity_id: !input presence_entity
    zone: !input work_zone
    event: leave
    id: zone_leave

  # Extra binary on/off (optional) – läuft immer als Trigger, wird später per choose "enabled" gefiltert
  - platform: state
    entity_id: !input extra_binary_sensor
    to: "on"
    id: bin_on

  - platform: state
    entity_id: !input extra_binary_sensor
    to: "off"
    id: bin_off

  # Calendar start/end (optional)
  - platform: calendar
    entity_id: !input calendar_entity
    event: start
    id: cal_start

  - platform: calendar
    entity_id: !input calendar_entity
    event: end
    id: cal_end

  # Pausen-Start/Ende (damit während Pause aus und danach ggf. wieder an)
  - platform: time
    at: !input pause1_start
    id: pause1_start
  - platform: time
    at: !input pause1_end
    id: pause1_end
  - platform: time
    at: !input pause2_start
    id: pause2_start
  - platform: time
    at: !input pause2_end
    id: pause2_end

condition: []

action:
  - choose:
      # -------------------------
      # START-Events (Zone enter / Binary ON / Calendar start)
      # -------------------------
      - conditions:
          - condition: template
            value_template: >
              {{ trigger.id in ['zone_enter','bin_on','cal_start'] }}
        sequence:
          # Filter: extra trigger nur wenn aktiviert
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ trigger.id == 'bin_on' and not extra_binary_enabled }}"
                sequence:
                  - stop: "Binary-Trigger nicht aktiviert."
              - conditions:
                  - condition: template
                    value_template: >
                      {{ trigger.id == 'cal_start' and not calendar_enabled }}
                sequence:
                  - stop: "Kalender-Trigger nicht aktiviert."
              - conditions:
                  - condition: template
                    value_template: >
                      {{ trigger.id == 'cal_start'
                         and calendar_title_contains|length > 0
                         and (trigger.calendar_event.summary | default('') | lower)
                            is not search(calendar_title_contains|lower) }}
                sequence:
                  - stop: "Kalender-Titel passt nicht zum Filter."

          # Nicht starten während Pause
          - condition: template
            value_template: "{{ not is_in_window }}"

          # Schon an? Dann nichts tun
          - condition: template
            value_template: "{{ is_state(tracking_switch, 'off') }}"

          # Optional bestätigen lassen
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ confirm_changes }}"
                sequence:
                  - service: "{{ notify_service }}"
                    data:
                      title: "Zeiterfassung"
                      message: "Starten?"
                      data:
                        actions:
                          - action: "ZEF_START_OK"
                            title: "Start"
                          - action: "ZEF_START_NO"
                            title: "Abbrechen"

                  - wait_for_trigger:
                      - platform: event
                        event_type: mobile_app_notification_action
                        event_data:
                          action: "ZEF_START_OK"
                      - platform: event
                        event_type: mobile_app_notification_action
                        event_data:
                          action: "ZEF_START_NO"
                    timeout: "00:02:00"
                    continue_on_timeout: false

                  - condition: template
                    value_template: "{{ wait.trigger.event.data.action == 'ZEF_START_OK' }}"

          # Start schalten
          - service: homeassistant.turn_on
            target:
              entity_id: !input tracking_switch

      # -------------------------
      # STOP-Events (Zone leave / Binary OFF / Calendar end)
      # -------------------------
      - conditions:
          - condition: template
            value_template: >
              {{ trigger.id in ['zone_leave','bin_off','cal_end'] }}
        sequence:
          # Filter: extra trigger nur wenn aktiviert
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ trigger.id == 'bin_off' and not extra_binary_enabled }}"
                sequence:
                  - stop: "Binary-Trigger nicht aktiviert."
              - conditions:
                  - condition: template
                    value_template: "{{ trigger.id == 'cal_end' and not calendar_enabled }}"
                sequence:
                  - stop: "Kalender-Trigger nicht aktiviert."
              - conditions:
                  - condition: template
                    value_template: >
                      {{ trigger.id == 'cal_end'
                         and calendar_title_contains|length > 0
                         and (trigger.calendar_event.summary | default('') | lower)
                            is not search(calendar_title_contains|lower) }}
                sequence:
                  - stop: "Kalender-Titel passt nicht zum Filter."

          # Schon aus? Dann nichts tun
          - condition: template
            value_template: "{{ is_state(tracking_switch, 'on') }}"

          # Optional bestätigen lassen
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ confirm_changes }}"
                sequence:
                  - service: "{{ notify_service }}"
                    data:
                      title: "Zeiterfassung"
                      message: "Beenden?"
                      data:
                        actions:
                          - action: "ZEF_STOP_OK"
                            title: "Beenden"
                          - action: "ZEF_STOP_NO"
                            title: "Abbrechen"

                  - wait_for_trigger:
                      - platform: event
                        event_type: mobile_app_notification_action
                        event_data:
                          action: "ZEF_STOP_OK"
                      - platform: event
                        event_type: mobile_app_notification_action
                        event_data:
                          action: "ZEF_STOP_NO"
                    timeout: "00:02:00"
                    continue_on_timeout: false

                  - condition: template
                    value_template: "{{ wait.trigger.event.data.action == 'ZEF_STOP_OK' }}"

          # Stop schalten
          - service: homeassistant.turn_off
            target:
              entity_id: !input tracking_switch

      # -------------------------
      # PAUSENLOGIK: Bei Pausenstart Zeiterfassung aus
      # -------------------------
      - conditions:
          - condition: template
            value_template: "{{ trigger.id in ['pause1_start','pause2_start'] }}"
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: >
                      {{ (trigger.id == 'pause1_start' and pause1_enabled)
                         or (trigger.id == 'pause2_start' and pause2_enabled) }}
                sequence:
                  - condition: state
                    entity_id: !input tracking_switch
                    state: "on"
                  - service: homeassistant.turn_off
                    target:
                      entity_id: !input tracking_switch

      # -------------------------
      # PAUSENLOGIK: Bei Pausenende ggf. wieder an, wenn "Startbedingung" erfüllt (Zone ODER Trigger)
      # -------------------------
      - conditions:
          - condition: template
            value_template: "{{ trigger.id in ['pause1_end','pause2_end'] }}"
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: >
                      {{ (trigger.id == 'pause1_end' and pause1_enabled)
                         or (trigger.id == 'pause2_end' and pause2_enabled) }}
                sequence:
                  # Nur wenn wir NICHT mehr in einer Pause sind
                  - condition: template
                    value_template: "{{ not is_in_window }}"

                  # Startbedingung: Zone ODER binary on ODER passender Calendar läuft gerade
                  - condition: template
                    value_template: >
                      {% set in_zone = (states(presence_entity) == state_attr(work_zone, 'friendly_name')) %}
                      {% set bin_ok = extra_binary_enabled and extra_binary_sensor != '' and is_state(extra_binary_sensor, 'on') %}
                      {% set cal_ok = calendar_enabled and calendar_entity != '' and is_state(calendar_entity, 'on') %}
                      {{ in_zone or bin_ok or cal_ok }}

                  # Wenn aus, dann wieder an (ohne Bestätigungsdialog, sonst nervt es bei Pausen sehr)
                  - condition: state
                    entity_id: !input tracking_switch
                    state: "off"
                  - service: homeassistant.turn_on
                    target:
                      entity_id: !input tracking_switch

    default: []
